### PR TITLE
More HTTP 1.1 updates/fixes

### PR DESCRIPTION
**Pull request by waynieack**

### CODE REVIEW

**Comment by hplato** [comment]
Did read_table_A get modified or just formatting changes?

**Comment by waynieack** [comment]
It now has descriptions for each section where an object is created. The
murdered formatting that Perl tidy did makes me want to take the current
copy and just move all the descriptions over to it.

**Comment by waynieack** [comment]
I deleted the revert pull request, but I don't think I should have.. I
reverted the changes on my local copy, pushed it to GIT, then put all the
changed files back (with the new copy of read_table_A and the update to fix
the redirect) and committed to GIT.

I made a pull request to your IA7 branch I am getting 30 conflicts with the
read_table_A.pl, so I guess you still need to revert the commit (or that
file).

**Comment by hplato** [comment]
I don’t think I can revert this because it’s deleted. The revert button is greyed out. Looking at that commit it doesn’t seem like I can back that out either.

**Pull request merged**
